### ISSUE TITLE
Trouble monitoring DA server

### ISSUE THREAD

**Issue by 33mhz** [hylasoft-usa/h-opc#14]
Hello, thanks for making this!

When trying to monitor a tag on a Simatic OPC server, it times out after exactly 42 seconds of waiting, every time. It gives this error:

```
System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at OpcRcw.Comn.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at OpcCom.ConnectionPoint.Advise(Object callback)
   at OpcCom.Da.Subscription.Advise()
   at OpcCom.Da.Subscription.add_DataChanged(DataChangedEventHandler value)
   at Opc.Da.Subscription.add_DataChanged(DataChangedEventHandler value)
   at Hylasoft.Opc.Da.DaClient.Monitor[T](String tag, Action`2 callback)
   at opc.Program.Main(String[] args) in Program.cs:line 74
```

I can read from the tag otherwise, using `client.Read<float>('path.to.float)`. Any ideas what to do? I'm not very familiar with OPC servers, if this is a default timeout or something... E.g., websockets require a "ping" to a server every ~40 seconds to maintain the connection.

**Comment by Tonny72** [comment]
Can you connect with a opc client like the matrikon opc explorer.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: 33MHz <notifications@github.com>
Datum: 10-12-2015  19:23  (GMT+01:00)
Aan: hylasoft-usa/h-opc <h-opc@noreply.github.com>
Onderwerp: [h-opc] Trouble monitoring DA server (#14)

Hello, thanks for making this!

When trying to monitor a tag on a Simatic OPC server, it times out after exactly 42 seconds of waiting, every time. It gives this error:

```
System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at OpcRcw.Comn.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at OpcCom.ConnectionPoint.Advise(Object callback)
   at OpcCom.Da.Subscription.Advise()
   at OpcCom.Da.Subscription.add_DataChanged(DataChangedEventHandler value)
   at Opc.Da.Subscription.add_DataChanged(DataChangedEventHandler value)
   at Hylasoft.Opc.Da.DaClient.Monitor[T](String tag, Action`2 callback)
   at opc.Program.Main(String[] args) in Program.cs:line 74
```

I can read from the tag otherwise, using `client.Read<float>('path.to.float)`. Any ideas what to do? I'm not very familiar with OPC servers, if this is a default timeout or something... E.g., websockets require a "ping" to a server every ~40 seconds to maintain the connection.

---
Reply to this email directly or view it on GitHub:
https://github.com/hylasoft-usa/h-opc/issues/14

**Comment by 33mhz** [comment]
Yes, I've been using the Softing OPC Classic Demo Client, but Matrikon could connect to it, too.

**Comment by 33mhz** [comment]
I had the `unsubscribe()` call commented out. Now with it in, the same error occurs, but now always at 64 seconds!

**Comment by 33mhz** [comment]
Sorry, scratch that. It did it 64, 64, 63, and now is going on 3+ minutes without crashing. So possibly a network issue? Hm.

**Comment by 33mhz** [comment]
I have values I can see are frequently changing by the 100th, but when I point the monitor at it and try to subscribe, it sits there for any amount of time (64 seconds, or 20 minutes) and does nothing until eventually saying the RPC server is unavailable.

**Comment by itajaja** [comment]
uhm... are you sure rpc is configured correctly? https://www.kepware.com/support/resource-library/connectivity-guides/remote-opc-da-dcom.pdf

**Comment by 33mhz** [comment]
@itajaja Not sure how I would know. The PC's networking and other systems seem to work without trouble. But from the operating system's standpoint, does monitoring a tag really need anything that calling a tag doesn't?

**Comment by jmbeach** [comment]
@itajaja What OPC server is being used in the test scripts? I want to try to run them on my localhost so I can contribute

**Comment by itajaja** [comment]
Hi @jmbeach and thanks for your interest. I used to test against [this sample server](https://opcfoundation.org/developer-tools/developer-kits-unified-architecture/sample-applications). I noticed now that it seems there is an [online version](http://www.opclabs.com/resources/product-information/articles/1094-public-demo-opc-xml-da-server-2) of it if you want to give it a try. Also, I am looking for a maintainer for h-opc, because unfortunately I changed job and I don't work with OPC technologies anymore. let me know if you are interested :)

**Comment by jmbeach** [comment]
That would be really cool!

**Comment by jmbeach** [comment]
And thanks for the reply! The online demo sounds perfect for testing

**Comment by jmbeach** [comment]
Can I close this issue @33mhz or are you still having issues?

**Comment by jmbeach** [comment]
@33mhz good deal
