### ISSUE TITLE
Adding monitors makes Dispose throws 'Collection was modified; enumeration operation may not execute.'

### ISSUE THREAD

**Issue by redsolo** [hylasoft-usa/h-opc#21]
I have a very simple Mqtt to Opc bridge program, that opens up a MQTT and sends to an OPC. Im using hylasoft and it can relay messages as it should. When I close the application I call Dispose() method on the UAClient which works fine.

But when I add monitoring to the application (for certain tags), and then when uaClient.Dispose() is called I get the following exception:
`System.InvalidOperationException occurred
  HResult=-2146233079
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
       at System.Collections.Generic.List`1.Enumerator.MoveNext()
       at Opc.Ua.Client.Session.RemoveSubscriptions(IEnumerable1 subscriptions)
       at Hylasoft.Opc.Ua.UaClient.Dispose()`

My monitoring code looks like this:
'            foreach (string tag in machineNames.Select(s => GetMachineTag(s, "SetFailureTime")))
            {
                uaClient.Monitor<object>(tag, (newValue, unsubscribe) =>
                {
                 // Do stuff
                });
            }'

**Comment by jmbeach** [comment]
Are you still having this issue? I would like to try to reproduce the problem

**Comment by aajdelbrid** [comment]
I am also experiencing this Exception when I stop my Windows Service. I am monitoring tags with the UAClient and when I call UAClient.Dispose in the Service's OnStop call I get this message. I have also experienced it with the "using () {}" syntax.

**Comment by jmbeach** [comment]
Which windows service?

**Comment by aajdelbrid** [comment]
Wow thanks for the fast response. I wrote a windows service to run an opc client it is call EPIQSOPCClient but this is irrelivent. I can produce the same error in a console application as well. It is the exact same error redsolo is receiving.

**Comment by jmbeach** [comment]
Gotcha. 
Can you tell me how to reproduce the problem? I didn't understand @redsolo's comment so well. Can you give me some sample code to run and I'll see if I can find the problem

**Comment by aajdelbrid** [comment]
It's when your calling the client dispose() while using monitoring. Here is a simple Console app that will reproduce the issue. The using example is comment out and below it is the same thing without using the using syntax. I just to show it throws the exception both ways. This will work until I hit enter on the console and the UaClient.Dispose() is called. Then I get the same error posted by redsolo

//using (Hylasoft.Opc.Ua.UaClient client = new Hylasoft.Opc.Ua.UaClient(new Uri(ConfigurationManager.AppSettings["opcServer"])))
            //{
            //    client.Connect();

            //    IEnumerable<UaNode> uaNodes = client.ExploreFolder(ConfigurationManager.AppSettings["opcFolder"]);

            //    foreach (var uaNode in uaNodes)
            //    {
            //        client.Monitor<object>(uaNode.Tag, (value, fn) => {

            //            Console.WriteLine("{0}:={1}", uaNode.Name, value);

            //        });
            //    }

            //    Console.Read();
            //}

            Hylasoft.Opc.Ua.UaClient client = new Hylasoft.Opc.Ua.UaClient(new Uri(ConfigurationManager.AppSettings["opcServer"]));

            client.Connect();

            IEnumerable<UaNode> uaNodes = client.ExploreFolder(ConfigurationManager.AppSettings["opcFolder"]);

            foreach (var uaNode in uaNodes)
            {
                client.Monitor<object>(uaNode.Tag, (value, fn) => {

                    Console.WriteLine("{0}:={1}", uaNode.Name, value);

                });
            }

            Console.Read();

            client.Dispose();

**Comment by jmbeach** [comment]
@redsolo I was able to reproduce the error, but I had to modify the H-Opc source funny enough. Are you using the [latest version of h-opc](https://www.nuget.org/packages/H.Opc/)? We recently changed the NuGet package name from `HylaSoft.Opc' to `H.Opc`. This was actually fixed in these commits, but I did not realize what they were fixing because I don't use UA as much as DA: d0c55c8beb535e71bbce5d63f91c871f543c0cb1 and 10c9738fef05d77281cc20a627679afef8bbfd66 

Let me know, because if you are using the latest, then I'll have do some more digging.

**Comment by aajdelbrid** [comment]
@jmbeach I did have the HylaSoft.Opc downloaded. Uninstalling that and grabbing the H.Opc from NuGet has fixed my issue. Thank You
