### ISSUE TITLE
h-opc-cli Unable to cast COM object

### ISSUE THREAD

**Issue by jmbeach** [hylasoft-usa/h-opc#41]
When connecting to OPC DA server with cli on 64x server. Think the issue has to do with 64x vs 32x. However, the problem does not occur on my 64x machine. 

```
An error occured when trying connecting to the server
The application ended unexpectedly.
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'OpcRcw.Comn.IOPCServerList2'. 

This operation failed because the QueryInterface call on the COM component for the interface with IID '{9DD0B56C-AD9E-43EE-8305-487F3188BF7A}' failed due to the following error: 

No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Opc.Server.Connect(URL url, ConnectData connectData)
   at Opc.Da.Server.Connect(URL url, ConnectData connectData)
   at Opc.Server.Connect()
   at Hylasoft.Opc.Da.DaClient.Connect() in c:\Users\giaco_000\Workspace\h-opc\h-opc\Da\DaClient.cs:line 49
   at Hylasoft.Opc.Cli.Program.Initialize(String[] args) in c:\Users\giaco_000\Workspace\h-opc\h-opc-cli\Program.cs:line 60
   at Hylasoft.Opc.Cli.Program.Main(String[] args) in c:\Users\giaco_000\Workspace\h-opc\h-opc-cli\Program.cs:line 21
To file an issue, visit http://github.com/hylasoft-usa/h-opc/issues
```

**Comment by jmbeach** [comment]
See my comment on this post http://stackoverflow.com/a/23749798/1834329
