### ISSUE TITLE
Unable to connect to UA Server when this is requesting a signed and encrypted connection

### ISSUE THREAD

**Issue by MikeSinge** [hylasoft-usa/h-opc#93]
Following fault message I get, when I try to establish a connection to an OPC UA Server signed and encrypted:
_Opc.Ua.ServiceResultException: ApplicationCertificate cannot be found.
   at Opc.Ua.Client.Session.Create(ApplicationConfiguration configuration, ConfiguredEndpoint endpoint, Boolean updateBeforeConnect, Boolean checkDomain, String sessionName, UInt32 sessionTimeout, IUserIdentity identity, IList`1 preferredLocales)
   at Hylasoft.Opc.Ua.UaClient.InitializeSession(Uri url)
   at Hylasoft.Opc.Ua.UaClient.Connect()
   at XY.Program.ProcessUa(String URI, List`1 entries, Int32 readperiod)_

I did already the advice to assign the X509 certificate. Does anyone give me an advice, how I can solve this issue?

BR,
Mike

**Comment by Berets** [comment]
I have the same problem, did you solve?
